language: python
matrix:
  include:
  - name: "3.7 Unit Test"
    python: "3.7"
    env: TEST_SUITE=suite_3_5_unit
  - name: "3.7 Integration Tests"
    python: "3.7 Integration tests"
    env: TEST_SUITE=suite_3_7_integration
  - name: "pypy Unit Tests"
    python: "pypy"
    env: TEST_SUITE=suite_pypy_unit
  script: test.py $TEST_SUITE
